public class Cat {

	// TODO: Declare a private String attribute called status
	private String status;
    
	// Declare a method to make the dog sit
	public void sit(){
        status = 'Sitting';
		// TODO: Set the status to 'Sitting'
	}
	
	// TODO: Just like the sit() method above; Declare a method to make the dog play 
    public void play(){
        status = 'playing';
    }
		// TODO: Set the status to 'Playing'
	

	// TODO: Declare a method to make the dog wag its tail
		// TODO: Set the status to 'Wagging Tail'

	
	// Declare a method that returns the status of the dog
	public String getStatus(){
        return status;
		// TODO: Return the status attribute
	}
}